version: '3.1'
services:
  postgre:
    image: 'postgres:11.10'
    container_name: 'pgsql_trello'
    ports:
      - "5431:5431"
    restart: always
    environment:
      - POSTGRES_USER=aleksandar
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=trello-api
    command: -p 5431